test_1_add_book (__main__.BookLoverTestSuite) ... ERROR
test_2_add_book (__main__.BookLoverTestSuite) ... ok
test_3_has_read (__main__.BookLoverTestSuite) ... ok
test_4_has_read (__main__.BookLoverTestSuite) ... ok
test_5_num_books_read (__main__.BookLoverTestSuite) ... ok
test_6_fav_books (__main__.BookLoverTestSuite) ... ERROR

======================================================================
ERROR: test_1_add_book (__main__.BookLoverTestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "booklover_test.py", line 11, in test_1_add_book
    actual = test_1.book_list
NameError: name 'test_1' is not defined

======================================================================
ERROR: test_6_fav_books (__main__.BookLoverTestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "booklover_test.py", line 70, in test_6_fav_books
    return fav['book_rating'] > 3
NameError: name 'fav' is not defined

----------------------------------------------------------------------
Ran 6 tests in 0.086s

FAILED (errors=2)
